### ISSUE TITLE
Authentication - Users without admin access can still access admin pages.

### ISSUE THREAD

**Issue by samkhodak** [WonderTix/WonderTix#242]
This is obviously an issue with auth. Users don't have the buttons to navigate to the admin pages, but they're still able to see the pages if they go to the correct urls.

**Comment by ben16williams** [comment]
I'm unable to access any admin pages while logged into with an account that does not have admin permissions as well as while not logged in. Any attempt to do so redirects to the front page when trying to access an admin page that does exists, or shows a 404 error trying to access a page that does not exists. I messed around with auth0 a little bit to make sure that all the tenants are as similar as possible, but am not sure what I did if anything that fixed this. It may be worth updating that behavior so that a non-admin can't gain insight into which pages exists to admins vs those that don't exist at all, but I think that this is fine for now.
