### ISSUE TITLE
Testing - Running Jest tests does not work correctly in vscode.

### ISSUE THREAD

**Issue by samkhodak** [WonderTix/WonderTix#279]

**Comment by jgreever** [comment]
Fix incoming. Issue is with Auth0 tokens and how the accounts were setup. We should _ideally_ be using developer tokens issued by the main WonderTix Auth0 dashboard instead of creating multiple accounts and not everyone having the same setup. For the time being, it is what it is, and if you want Jest tests working, **you will have to modify or recreate your application and API in Auth0 to match the documentation that will be provided by me shortly.**

**Comment by jgreever** [comment]
fix merged into main. Again, this does require a different type of key in order to run the tests locally. This is currently in the process of being mocked so we don't hammer the API. If you are using the proper tokens, the tests run just fine, but those tokens are different than the ones used to setup authentication.

closing this ticket and creating a new one to refactor the jest tests to use a mock auth0 return response.
