### ISSUE TITLE
Add popup to communicate a failed checkout for donations page

### ISSUE THREAD

**Issue by ben16williams** [WonderTix/WonderTix#539]

**Comment by ReidLuttrell** [comment]
@ben16williams Upon reading the stripe documentation and testing myself, because donation and regular checkout sessions go through the stripe page, checkout failures are indicated to the customer by the stripe itself, and when failed will go to the cancel_url defined in the session object, this includes session expiring. The only thing that needs to be dealt with is cancelling the order in prisma, which is already done. On the other hand, the card reader code has handling and error popups because they are dealt with entirely within the playhouse website, and never navigate to stripe.
![WWQjsYf](https://github.com/WonderTix/WonderTix/assets/127803000/b4f733be-5d24-48da-92bf-24dcff83144a)

**Comment by CoalontheFire** [comment]
@ben16williams 
Closing this issue for the reasons that Reid posted in last comment.
